# Generated by Django 5.1.3 on 2024-11-19 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnscan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created'),
        ),
        migrations.AlterField(
            model_name='host',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='operativesystemclass',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created'),
        ),
        migrations.AlterField(
            model_name='operativesystemclass',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='operativesystemmatch',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created'),
        ),
        migrations.AlterField(
            model_name='operativesystemmatch',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='port',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created'),
        ),
        migrations.AlterField(
            model_name='port',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='portservice',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created'),
        ),
        migrations.AlterField(
            model_name='portservice',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='scannerhistory',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created'),
        ),
        migrations.AlterField(
            model_name='scannerhistory',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated'),
        ),
    ]
