# Generated by Django 5.1.3 on 2024-11-22 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnscan', '0002_alter_host_created_on_alter_host_updated_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operativesystemmatch',
            name='accuracy',
            field=models.PositiveIntegerField(),
        ),
    ]
