# Generated by Django 5.1.3 on 2024-11-22 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnscan', '0003_alter_operativesystemmatch_accuracy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operativesystemmatch',
            name='line',
            field=models.PositiveIntegerField(),
        ),
    ]
