# Generated by Django 5.1.3 on 2024-11-27 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnscan', '0004_alter_operativesystemmatch_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operativesystemclass',
            name='accuracy',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='port',
            name='portid',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='port',
            name='reason_ttl',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='portservice',
            name='conf',
            field=models.PositiveIntegerField(),
        ),
    ]
